### ISSUE TITLE
Object value strings have extra quotes.

### ISSUE THREAD

**Issue by pastelsky** [ArikMaor/extended-define-webpack-plugin#1]
I use the extended webpack plugin as such:

``` javascript
      new ExtendedDefinePlugin({
        GlobalKey:  { 
              numberKey: 1234,
              stringKey: "foo",
          },
      }),
```

But when the output I get is:

``` javascript
console.log(GlobalKey.stringKey,  typeof GlobalKey.stringKey);
// Outputs ""foo"" string
```

UPDATE:
So after wasting a good 2 hours, I find out its happening because I'm using multiple webpack configs — server and client, and the unexpected behaviour always occurs in the second config.

This is because this library is directly modifying the params sent to it (which are passed by 
reference). Ouch. Use ESLint `no-param-reassign` maybe?

**Comment by arikmaor** [comment]
I recommend using [EnvironmentPlugin](https://webpack.github.io/docs/list-of-plugins.html#environmentplugin) instead of this.

Sorry for your troubles. When I wrote this, webpack didn't include the EnvironmentPlugin, but now it's best to use this one as I don't maintain this project anymore.

**Comment by pastelsky** [comment]
EnvironmentPlugin seems to work best with environment variables. 
I've raised a small pull request #2 to fix this behaviour — might be helpful for people using multiple webpack config objects.
