### ISSUE TITLE
Add support for webpack 2

### ISSUE THREAD

**Issue by joeyfigaro** [ArikMaor/extended-define-webpack-plugin#3]
If I have some time, will look into what's required to support webpack 2. Have no experience with writing webpack plugins, but would be happy to put up a PR.

**Comment by afilp** [comment]
Thanks, it shows a warning, it would be nice to upgrade this for webpack 2.

**Comment by arikmaor** [comment]
can someone copy the warning?
10x in advance

**Comment by Chris3773** [comment]
When running webpack 2.2.0:

`npm WARN extended-define-webpack-plugin@0.1.2 requires a peer of webpack@^1.12.9 but none was installed.`

**Comment by arikmaor** [comment]
Warning should be removed now bafa12c67deb9b9f7ddb3a8b77b12b53159cadc8 (update to 0.1.3)
Can you confirm?

I haven't had the chance to test this with webpack 2, but it should work the same

**Comment by Chris3773** [comment]
I can confirm the warning is no longer there for webpack 2.0.
